/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as AdminStudentsRouteImport } from "./routes/admin.students";
import { Route as AdminHostelsRouteImport } from "./routes/admin.hostels";
import { Route as AdminAllocationRouteImport } from "./routes/admin.allocation";
import { Route as AdminMatchingRouteImport } from "./routes/admin.matching";
import { Route as AdminComplaintsRouteImport } from "./routes/admin.complaints";
import { Route as AdminAttendanceRouteImport } from "./routes/admin.attendance";
import { Route as AdminReportsRouteImport } from "./routes/admin.reports";
import { Route as ApplyRouteImport } from "./routes/apply";
import { Route as AttendanceRouteImport } from "./routes/attendance";
import { Route as ComplaintsRouteImport } from "./routes/complaints";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as PaymentsRouteImport } from "./routes/payments";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as RequestsRouteImport } from "./routes/requests";
import { Route as RoomChangeRouteImport } from "./routes/room-change";
import { Route as RoommatesRouteImport } from "./routes/roommates";
import { Route as WardenRouteImport } from "./routes/warden";
import { Route as HostelsIndexRouteImport } from "./routes/hostels.index";
import { Route as HostelsHostelIdRouteImport } from "./routes/hostels.$hostelId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
});
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: "/admin/students",
  path: "/admin/students",
  getParentRoute: () => rootRouteImport,
});
const AdminHostelsRoute = AdminHostelsRouteImport.update({
  id: "/admin/hostels",
  path: "/admin/hostels",
  getParentRoute: () => rootRouteImport,
});
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: "/admin/allocation",
  path: "/admin/allocation",
  getParentRoute: () => rootRouteImport,
});
const AdminMatchingRoute = AdminMatchingRouteImport.update({
  id: "/admin/matching",
  path: "/admin/matching",
  getParentRoute: () => rootRouteImport,
});
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: "/admin/complaints",
  path: "/admin/complaints",
  getParentRoute: () => rootRouteImport,
});
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: "/admin/attendance",
  path: "/admin/attendance",
  getParentRoute: () => rootRouteImport,
});
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: "/admin/reports",
  path: "/admin/reports",
  getParentRoute: () => rootRouteImport,
});
const ApplyRoute = ApplyRouteImport.update({
  id: "/apply",
  path: "/apply",
  getParentRoute: () => rootRouteImport,
});
const AttendanceRoute = AttendanceRouteImport.update({
  id: "/attendance",
  path: "/attendance",
  getParentRoute: () => rootRouteImport,
});
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: "/complaints",
  path: "/complaints",
  getParentRoute: () => rootRouteImport,
});
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
});
const PaymentsRoute = PaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
});
const RequestsRoute = RequestsRouteImport.update({
  id: "/requests",
  path: "/requests",
  getParentRoute: () => rootRouteImport,
});
const RoomChangeRoute = RoomChangeRouteImport.update({
  id: "/room-change",
  path: "/room-change",
  getParentRoute: () => rootRouteImport,
});
const RoommatesRoute = RoommatesRouteImport.update({
  id: "/roommates",
  path: "/roommates",
  getParentRoute: () => rootRouteImport,
});
const WardenRoute = WardenRouteImport.update({
  id: "/warden",
  path: "/warden",
  getParentRoute: () => rootRouteImport,
});
const HostelsIndexRoute = HostelsIndexRouteImport.update({
  id: "/hostels/",
  path: "/hostels/",
  getParentRoute: () => rootRouteImport,
});
const HostelsHostelIdRoute = HostelsHostelIdRouteImport.update({
  id: "/hostels/$hostelId",
  path: "/hostels/$hostelId",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminHostelsRoute: AdminHostelsRoute,
  AdminAllocationRoute: AdminAllocationRoute,
  AdminMatchingRoute: AdminMatchingRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminReportsRoute: AdminReportsRoute,
  ApplyRoute: ApplyRoute,
  AttendanceRoute: AttendanceRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RequestsRoute: RequestsRoute,
  RoomChangeRoute: RoomChangeRoute,
  RoommatesRoute: RoommatesRoute,
  WardenRoute: WardenRoute,
  HostelsHostelIdRoute: HostelsHostelIdRoute,
  HostelsIndexRoute: HostelsIndexRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
