/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RoomChangeRouteImport } from './routes/room-change'
import { Route as RoommatesRouteImport } from './routes/roommates'
import { Route as WardenRouteImport } from './routes/warden'
import { Route as AdminAllocationRouteImport } from './routes/admin.allocation'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminHostelsRouteImport } from './routes/admin.hostels'
import { Route as AdminMatchingRouteImport } from './routes/admin.matching'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as HostelsIndexRouteImport } from './routes/hostels.index'
import { Route as HostelsHostelIdRouteImport } from './routes/hostels.$hostelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomChangeRoute = RoomChangeRouteImport.update({
  id: '/room-change',
  path: '/room-change',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesRoute = RoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const WardenRoute = WardenRouteImport.update({
  id: '/warden',
  path: '/warden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostelsRoute = AdminHostelsRouteImport.update({
  id: '/hostels',
  path: '/hostels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchingRoute = AdminMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const HostelsIndexRoute = HostelsIndexRouteImport.update({
  id: '/hostels/',
  path: '/hostels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelsHostelIdRoute = HostelsHostelIdRouteImport.update({
  id: '/hostels/$hostelId',
  path: '/hostels/$hostelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/attendance': typeof AttendanceRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRoute
  '/room-change': typeof RoomChangeRoute
  '/roommates': typeof RoommatesRoute
  '/warden': typeof WardenRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/hostels': typeof AdminHostelsRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/hostels/$hostelId': typeof HostelsHostelIdRoute
  '/hostels/': typeof HostelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/attendance': typeof AttendanceRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRoute
  '/room-change': typeof RoomChangeRoute
  '/roommates': typeof RoommatesRoute
  '/warden': typeof WardenRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/hostels': typeof AdminHostelsRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/hostels/$hostelId': typeof HostelsHostelIdRoute
  '/hostels': typeof HostelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/attendance': typeof AttendanceRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRoute
  '/room-change': typeof RoomChangeRoute
  '/roommates': typeof RoommatesRoute
  '/warden': typeof WardenRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/hostels': typeof AdminHostelsRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/hostels/$hostelId': typeof HostelsHostelIdRoute
  '/hostels/': typeof HostelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/attendance'
    | '/complaints'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/register'
    | '/requests'
    | '/room-change'
    | '/roommates'
    | '/warden'
    | '/admin/allocation'
    | '/admin/attendance'
    | '/admin/complaints'
    | '/admin/hostels'
    | '/admin/matching'
    | '/admin/reports'
    | '/admin/students'
    | '/hostels/$hostelId'
    | '/hostels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/attendance'
    | '/complaints'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/register'
    | '/requests'
    | '/room-change'
    | '/roommates'
    | '/warden'
    | '/admin/allocation'
    | '/admin/attendance'
    | '/admin/complaints'
    | '/admin/hostels'
    | '/admin/matching'
    | '/admin/reports'
    | '/admin/students'
    | '/hostels/$hostelId'
    | '/hostels'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/attendance'
    | '/complaints'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/register'
    | '/requests'
    | '/room-change'
    | '/roommates'
    | '/warden'
    | '/admin/allocation'
    | '/admin/attendance'
    | '/admin/complaints'
    | '/admin/hostels'
    | '/admin/matching'
    | '/admin/reports'
    | '/admin/students'
    | '/hostels/$hostelId'
    | '/hostels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AttendanceRoute: typeof AttendanceRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RequestsRoute: typeof RequestsRoute
  RoomChangeRoute: typeof RoomChangeRoute
  RoommatesRoute: typeof RoommatesRoute
  WardenRoute: typeof WardenRoute
  HostelsHostelIdRoute: typeof HostelsHostelIdRoute
  HostelsIndexRoute: typeof HostelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-change': {
      id: '/room-change'
      path: '/room-change'
      fullPath: '/room-change'
      preLoaderRoute: typeof RoomChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates': {
      id: '/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof RoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warden': {
      id: '/warden'
      path: '/warden'
      fullPath: '/warden'
      preLoaderRoute: typeof WardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hostels': {
      id: '/admin/hostels'
      path: '/hostels'
      fullPath: '/admin/hostels'
      preLoaderRoute: typeof AdminHostelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matching': {
      id: '/admin/matching'
      path: '/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AdminMatchingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hostels/': {
      id: '/hostels/'
      path: '/hostels'
      fullPath: '/hostels/'
      preLoaderRoute: typeof HostelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostels/$hostelId': {
      id: '/hostels/$hostelId'
      path: '/hostels/$hostelId'
      fullPath: '/hostels/$hostelId'
      preLoaderRoute: typeof HostelsHostelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAllocationRoute: typeof AdminAllocationRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminHostelsRoute: typeof AdminHostelsRoute
  AdminMatchingRoute: typeof AdminMatchingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllocationRoute: AdminAllocationRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminHostelsRoute: AdminHostelsRoute,
  AdminMatchingRoute: AdminMatchingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AttendanceRoute: AttendanceRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RequestsRoute: RequestsRoute,
  RoomChangeRoute: RoomChangeRoute,
  RoommatesRoute: RoommatesRoute,
  WardenRoute: WardenRoute,
  HostelsHostelIdRoute: HostelsHostelIdRoute,
  HostelsIndexRoute: HostelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
